version: '3.7'
services:
  db:
    image: postgres:12.2
    container_name: todo-server-db
    environment:
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_DB: ${TYPEORM_DATABASE}
    tty: true
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
  # test-db:
  #   image: postgres:12.2-alpine
  #   container_name: todo-server-testdb
  #   environment:
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_USER: postgres
  #     POSTGRES_DB: todo-app-test
  #   tty: true
  #   volumes:
  #     - ./pgdata:/var/lib/postgresql/testdata
  #   ports:
  #     - 5433:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
