version: '3.7'
services:
  db:
    image: postgres
    container_name: todo-server-db
    environment:
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_DB: ${TYPEORM_DATABASE}
    tty: true
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
